### ISSUE TITLE
GIT Clone steps in Instructions refer to old repository name

### ISSUE THREAD

**Issue by TesterTesterson1004** [MicrosoftLearning/AI-102-AIEngineer.zh-cn#1]
# Module: (all)
#### Step: 00

Description of issue

The GIT Clone steps in the lab steps refer to the old repository, and should be updated to point to this new repository:

打开面板 (Shift+Ctrl+P) 并运行 Git: Clone 命令，将 https://github.com/MicrosoftLearning/AI-102ZH-Designing-and-Implementing-a-Microsoft-Azure-AI-Solution 存储库克隆到本地文件夹（具体克隆到哪个文件夹无关紧要）。

**Comment by olprod** [comment]
Hello contributor,

Thank you for your contribution! We are processing your suggestions and we will update you shortly.   

Kind regards,  

Microsoft Worldwide Learning Team

**Comment by Chenpeng21** [comment]
This issue can no longer be reproduced.
![image](https://user-images.githubusercontent.com/93902755/181456351-b9f65249-2a8b-42b5-a0ca-4c03d4e38ff1.png)
