### ISSUE TITLE
Container Image naming not valid 

### ISSUE THREAD

**Issue by Universo-Ap00** [MicrosoftLearning/AI-102-AIEngineer.zh-cn#2]
# Module: 04
#### Step: 01

Description of issue:

- The naming scheme is different in these localized instructions vs the English. The naming for containers is limited via Security policy and must be named 'ai + Lab instance ID' where Lab ID is found in the Help tab of the instructions Panel. Shown in the screenshot below of the english version:

![image](https://user-images.githubusercontent.com/53233868/225419170-93631960-4e95-4f19-8332-a6e391038f1e.png)

Lab Instance ID Found here on Help tab: 
![image](https://user-images.githubusercontent.com/53233868/225419405-dd9614b7-c8c4-4843-b38b-d74d013c5733.png)

Repro steps:
1. Change instructions from a Unique name for the container to using 'ai + Lab ID'

**Comment by olprod** [comment]
Hello contributor,

Thank you for your contribution! We are processing your suggestions and we will update you shortly.   

Kind regards,  

Microsoft Worldwide Learning Team

**Comment by Universo-Ap00** [comment]
Replacement to be added for this issue
