### ISSUE TITLE
Mod 20 Instruction Updates 

### ISSUE THREAD

**Issue by Universo-Ap00** [MicrosoftLearning/AI-102-AIEngineer.zh-cn#3]
# Module: 20
## Lab/Demo: Read API

Description of issue:

The ZH version of Mod 20 is lacking instructional updates needed to match the english version. Curious to if there is a timeframe for these updated instructions or if it is known, but needs to be put out there. 

Example in screenshot:

![image](https://user-images.githubusercontent.com/53233868/225989936-a78b63d4-6b62-403c-ab91-ebab964cbebe.png)

**Comment by olprod** [comment]
Hello contributor,

Thank you for your contribution! We are processing your suggestions and we will update you shortly.   

Kind regards,  

Microsoft Worldwide Learning Team

**Comment by chriscarty00** [comment]
[Locfile](https://wus-000.icms.osi.office.net/vantagepoint/QueryPanel.aspx?Tenant=CAICritical&Query=PFZQUT48TEZPPkZhbHNlPC9MRk8%2bPElEPkZhbHNlPC9JRD48RUxDPkZhbHNlPC9FTEM%2bPEFNUD5GYWxzZTwvQU1QPjxTT0hSSVI%2bRmFsc2U8L1NPSFJJUj48U0hSUD5UcnVlPC9TSFJQPjxTQVRPPlRydWU8L1NBVE8%2bPFNBTE8%2bRmFsc2U8L1NBTE8%2bPFFFPj4yPC9RRT48UVQ%2bPjxRUiBJZD0iMSIgQ1BJRD0iMCI%2bQ3VycmVudDtGaWxlcztIb3N0IENvbnRlbnQgU3RvcmU7RXF1YWw7V1dMPC9RUj48UVIgSWQ9IjIiIENQSUQ9IjAiPmFuZDtDdXJyZW50O0ZpbGVzO0hvc3QgRmlsZSBSZWZlcmVuY2U7RXF1YWw7NTAzMDAuSW5zdHJ1Y3Rpb25zLjIwLW9jci5tZDwvUVI%2bPFFSIElkPSIzIiBDUElEPSIwIj5hbmQ7Q3VycmVudDtMb2NGaWxlcztMYW5ndWFnZTtFcXVhbDtDaGluZXNlIChTaW1wbGlmaWVkKTwvUVI%2bPC9RVD48Ukc%2bPEdDPk5VTEw8L0dDPjwvUkc%2bPC9WUFE%2b) is at HB on 12/1/2022 3:43:06 PM - which indicates its out of sync
Latest update to the [US page](https://github.com/MicrosoftLearning/AI-102-AIEngineer/blob/master/Instructions/20-ocr.md) is 1/18/2023

**Comment by chriscarty00** [comment]
Lens shows the locfile checked in on 2023-01-08
FileTrackingDistinct 
| where BranchName == 'LAB_AI-102' and FileName contains  '50300.Instructions.20-ocr.md' and Cultures == 'zh-CN'
| order by EventTime

**Comment by chriscarty00** [comment]
Question to the MS PM - do we need this to go back into loc?

**Comment by chriscarty00** [comment]
This has been updated 6/16/2023 and is now in sync with the US
